// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAISyLlDq7DEElyAY73GKFuaB04meb3yKQ',
    appId: '1:885232569486:web:60acfed281913da0a04ddf',
    messagingSenderId: '885232569486',
    projectId: 'instagram-clone-8dcf8',
    authDomain: 'instagram-clone-8dcf8.firebaseapp.com',
    storageBucket: 'instagram-clone-8dcf8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK8rAs_H3jCgR9e2UJuYuM-qUYJu-GTCU',
    appId: '1:885232569486:android:f70fed50a18b9ddaa04ddf',
    messagingSenderId: '885232569486',
    projectId: 'instagram-clone-8dcf8',
    storageBucket: 'instagram-clone-8dcf8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDisZRC6je01Zt0fDJinmizEC3yPsMLX4g',
    appId: '1:885232569486:ios:0b99663c44d7d06aa04ddf',
    messagingSenderId: '885232569486',
    projectId: 'instagram-clone-8dcf8',
    storageBucket: 'instagram-clone-8dcf8.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDisZRC6je01Zt0fDJinmizEC3yPsMLX4g',
    appId: '1:885232569486:ios:14be9f32f7a1284ca04ddf',
    messagingSenderId: '885232569486',
    projectId: 'instagram-clone-8dcf8',
    storageBucket: 'instagram-clone-8dcf8.appspot.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
